<?php

namespace Dekalee\MailjetBundle\Repository;

use Dekalee\MailjetBundle\Entity\ContactList;
use Doctrine\ORM\EntityRepository;

/**
 * ContactListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactListRepository extends EntityRepository
{
    /**
     * @param $name
     *
     * @return ContactList
     */
    public function findOneByName($name)
    {
        return $this->findOneBy(['name' => $name]);
    }
}
