<?php

namespace Dekalee\MailjetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactListRepository extends EntityRepository
{
}
