parameters:
    dekalee_mailjet.client.class: Dekalee\MailjetBundle\Client\DekaleeClient

services:
    dekalee_mailjet.client:
        class: '%dekalee_mailjet.client.class%'
        arguments:
            - '%dekalee_mailjet.key.api%'
            - '%dekalee_mailjet.key.secret%'
