parameters:
    dekalee_mailet.creator.contact.class: Dekalee\MailjetBundle\Creator\ContactCreator

services:
    dekalee_mailet.creator.contact:
        class: '%dekalee_mailet.creator.contact.class%'
        arguments:
            - '@dekalee_mailjet.client'
