parameters:
    dekalee_mailet.subscriber.contact_list.class: Dekalee\MailjetBundle\Manager\ContactListSubscriber
    dekalee_mailjet.unsubscriber.contact_list.class: Dekalee\MailjetBundle\Manager\ContactListUnsubscriber

services:
    dekalee_mailet.subscriber.contact_list:
        class: '%dekalee_mailet.subscriber.contact_list.class%'
        arguments:
            - '@dekalee_mailjet.convertor.contact_list'
            - '@dekalee_mailet.creator.contact'
    dekalee_mailjet.unsubscriber.contact_list:
        class: '%dekalee_mailjet.unsubscriber.contact_list.class%'
        arguments:
            - '@dekalee_mailjet.convertor.contact_list'
            - '@dekalee_mailjet.client'
