parameters:
    dekalee_mailjet.repository.contact_list.class: Dekalee\MailjetBundle\Repository\ContactListRepository
    dekalee_mailjet.entity.contact_list.class: Dekalee\MailjetBundle\Entity\ContactList

services:
    dekalee_mailjet.repository.contact_list:
        class: '%dekalee_mailjet.repository.contact_list.class%'
        factory: ['@doctrine.orm.local_entity_manager', getRepository]
        arguments:
            - '%dekalee_mailjet.entity.contact_list.class%'
